import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav>
					<ul>
						<li>
							<Link href={'/csr'}>CSR</Link>
						</li>
						<li>
							<Link href={'/isr'}>ISR</Link>
						</li>
						<li>
							<Link href={'/ssg'}>SSG</Link>
						</li>
						<li>
							<Link href={'/ssr'}>SSR</Link>
						</li>
					</ul>
				</nav>
				<main>{children}</main>
			</body>
		</html>
	);
}
