import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="bg-gray-900 p-4 flex justify-start items-center">
					<ul className="flex space-x-5 text-white">
						<li>
							<Link href={'/csr'}>
								<p className="cursor-pointer hover:text-gray-300">CSR</p>
							</Link>
						</li>
						<li>
							<Link href={'/isr'}>
								<p className="cursor-pointer hover:text-gray-300">ISR</p>
							</Link>
						</li>
						<li>
							<Link href={'/ssg'}>
								<p className="cursor-pointer hover:text-gray-300">SSG</p>
							</Link>
						</li>
						<li>
							<Link href={'/ssr'}>
								<p className="cursor-pointer hover:text-gray-300">SSR</p>
							</Link>
						</li>
					</ul>
				</nav>
				<main>{children}</main>
			</body>
		</html>
	);
}
